# Playing
SKIP_SONGS = True
SKIP_DELAY = 35  # seconds; > 30 so Spotify counts the play as a stream
RANDOM_ORDER_TRACKS = True

# API
CLIENT_ID = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CLIENT_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
REDIRECT_URI = "http://localhost:8888/callback/"

# Account
USERNAME = "USERNAME"
PLAYLIST_NAME = "PLAYLIST"
SERVER_NAMES = ["SERVER-1", "SERVER-2", "SERVER-3", "SERVER-4"]

# Checks
CHECKS_BEFORE_PLAYING = 5
TIME_BETWEEN_CHECKS = 30

# Errors
RETRY_TIME = 10

# Notifications
NOTIFICATION_ENABLED = True
NOTIFICATION_FILENAME = "telegram.conf"
UPDATE_PLAYLIST_NOTIFICATION = "Updated playlist 🎵"
START_PROGRAM_NOTIFICATION = "Starting program 🏁"
START_PLAYING_NOTIFICATION = "Started playing 🟩"
STOP_PLAYING_NOTIFICATION = "Stopped playing 🟥"
SEND_NOTIFICATION_ON_ERROR = True

# Timelogging
TIMELOG_FILENAME = "time.txt"
