CLIENT_ID = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CLIENT_SECRET = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

SERVER_NAMES = ["AFK_SPOTIFY_CLIENT", "DESKTOP-SERVER"]
PLAYLIST_NAME = "AFK_PLAYLIST"
TIME_BETWEEN_CHEAKS = .5 * 60 # 30 Seconds
CHEAKS_BEFORE_PLAYING = 2
RANDOM_ORDER_TRACKS = True
SKIP_SONGS = True
SKIP_DELAY = 35
RETRY_TIME = 10