# PLAYING
SKIP_SONGS = True
SKIP_DELAY = 35
RANDOM_ORDER_TRACKS = True
PLAYLIST_NAME = "PLAYLIST"

# API
CLIENT_ID = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CLIENT_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
REDIRECT_URI = "http://localhost:8888/callback/"

# ACCOUNT
USERNAME = "USERNAME"
SERVER_NAMES = ["SERVER-1", "SERVER-2", "SERVER-3", "SERVER-4"]

# CHEAKS
CHEAKS_BEFORE_PLAYING = 5
TIME_BETWEEN_CHEAKS = 30

# ERRORS
RETRY_TIME = 10