#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OPTIONS_FILE="$REPO_DIR/options.py"
TELEGRAM_CONF="$REPO_DIR/telegram.conf"

# write_opt KEY PYTHON_LITERAL replaces `KEY = ...` in options.py in place.
write_opt() {
  python3 - "$OPTIONS_FILE" "$1" "$2" <<'PY'
import re, sys
path, key, literal = sys.argv[1:]
src = open(path).read()
new, count = re.subn(rf"(?m)^{key} = .*$", f"{key} = {literal}", src)
if count == 0:
    new = src.rstrip("\n") + f"\n{key} = {literal}\n"
open(path, "w").write(new)
PY
  printf '  %s✓ wrote%s %s → options.py\n' "$GREEN" "$RESET" "$1"
}

# write_opt_str KEY VALUE quotes VALUE as a Python string first.
write_opt_str() {
  write_opt "$1" "$(python3 -c 'import sys; print(repr(sys.argv[1]))' "$2")"
}

banner "SpotiAFK setup"

# ── Stage 1: Spotify developer app ────────────────────────────────────────
stage "Spotify developer app"
say "SpotiAFK needs its own Spotify app so it can use the Web API."
open_url "https://developer.spotify.com/dashboard"
step "Log in and click 'Create app'."
step "Pick any name and description, and tick the Web API checkbox."
step "In the app's Settings, add this Redirect URI and save:"
say  "    http://localhost:8888/callback/"
step "Still in Settings, copy the Client ID."
ask CLIENT_ID "Paste the Client ID:"
step "Click 'View client secret' and copy it."
ask_secret CLIENT_SECRET "Paste the Client secret:"
ask REDIRECT_URI "Redirect URI [Enter for http://localhost:8888/callback/]:"
[[ -z "${REDIRECT_URI}" ]] && REDIRECT_URI="http://localhost:8888/callback/"
write_opt_str CLIENT_ID "$CLIENT_ID"
write_opt_str CLIENT_SECRET "$CLIENT_SECRET"
write_opt_str REDIRECT_URI "$REDIRECT_URI"
note "options.py is not in .gitignore, so don't commit it now that it holds your secret."

# ── Stage 2: account, playlist, and devices ───────────────────────────────
stage "Account, playlist, and devices"
open_url "https://www.spotify.com/account/profile/"
step "Copy your username from the profile page."
ask SPOTIFY_USERNAME "Your Spotify username:"
step "Name the playlist SpotiAFK should play from (it must exist in your library)."
ask PLAYLIST_NAME "Playlist name:"
say  "Now the devices SpotiAFK may play on (your 'servers')."
step "Open Spotify, click the 'Connect to a device' icon, and note the exact device names."
ask SERVER_NAMES_CSV "Device names, comma-separated:"
write_opt_str USERNAME "$SPOTIFY_USERNAME"
write_opt_str PLAYLIST_NAME "$PLAYLIST_NAME"
write_opt SERVER_NAMES "$(python3 -c 'import sys; print([n.strip() for n in sys.argv[1].split(",") if n.strip()])' "$SERVER_NAMES_CSV")"

# ── Stage 3: Telegram notifications (optional) ────────────────────────────
stage "Telegram notifications (optional)"
if confirm "Do you want Telegram notifications?"; then
  open_url "https://t.me/BotFather"
  step "Send /newbot to BotFather and follow the prompts."
  step "Copy the bot token BotFather gives you."
  ask_secret TELEGRAM_TOKEN "Paste the bot token:"
  open_url "https://t.me/userinfobot"
  step "Press Start; it replies with your numeric id."
  ask TELEGRAM_CHAT_ID "Paste your chat id:"
  printf '[telegram]\ntoken = %s\nchat_id = %s\n' "$TELEGRAM_TOKEN" "$TELEGRAM_CHAT_ID" > "$TELEGRAM_CONF"
  chmod 600 "$TELEGRAM_CONF"
  printf '  %s✓ wrote%s telegram.conf (chmod 600)\n' "$GREEN" "$RESET"
  write_opt NOTIFICATION_ENABLED "True"
  step "Open a chat with your new bot and press Start, or it can't message you."
  pause
else
  write_opt NOTIFICATION_ENABLED "False"
  note "Notifications disabled; re-run this wizard to turn them on later."
fi

# ── Stage 4: install and first run ────────────────────────────────────────
stage "Install and first run"
if command -v pipenv >/dev/null 2>&1; then
  if confirm "Run 'pipenv install' now?"; then
    (cd "$REPO_DIR" && pipenv install)
  fi
else
  warn "pipenv not found; install it first (pip install pipenv), then run: pipenv install"
  SKIPPED+=("pipenv install")
fi
say "Start SpotiAFK with:"
say "    pipenv run python3 spotiAFK.py"
say "The first run opens a Spotify page asking you to authorize the app once."
say "For a supervised run that restarts on crashes, use ./restarter.sh instead."
pause "That's everything. Press Enter for the summary."

finish
